name: "Flutter Web App Deployment"
description: "Deploys the Flutter web application to GitHub pages."

branding:
  icon: "code"
  color: "blue"

inputs:
  branch:
    description: "The branch where the web app will be deployed."
    required: false
    default: "gh-pages"
  href:
    description: "The base href for the Flutter web application."
    required: false
    default: "/"
  name:
    description: "The name for Git commits."
    required: false
    default: "${{github.actor}}"
  email:
    description: "The email address for Git commits."
    required: false
    default: "${{github.actor}}@users.noreply.github.com"

runs:
  using: "composite"
  steps:
    - name: Configure Flutter for web
      shell: bash
      run: |
        flutter config --enable-web
        flutter create --platforms=web .

    - name: Build the Flutter web application
      shell: bash
      run: |
        flutter pub get
        flutter build web --release --base-href "${{inputs.href}}"

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "${{inputs.name}}"
        git config --global user.email "${{inputs.email}}"
        git config --global --add safe.directory /github/workspace

    - name: Prepare the deployment branch
      shell: bash
      run: |
        git checkout -B "${{inputs.branch}}"
        git push origin "${{inputs.branch}}" -f

    - name: Deploy to GitHub pages
      shell: bash
      run: |
        git add build/web/ -f
        git commit -m "Deploy Flutter Web Application"
        git push origin $(git subtree split --prefix=build/web/):${{inputs.branch}} -f
