name: "Flutter Web App Deployment"
description: "Deploys the Flutter web application to GitHub pages."
author: "G1Joshi"

branding:
  icon: "code"
  color: "blue"

inputs:
  working-directory:
    description: "Working directory for Flutter commands"
    required: false
    default: "."
  run-tests:
    description: "Whether to run tests before building"
    required: false
    default: "true"
  build-target:
    description: "Target file for Flutter build"
    required: false
    default: "lib/main.dart"

outputs:
  page-url:
    description: "URL of the deployed GitHub Pages site"
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup Flutter
      uses: subosito/flutter-action@v2

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: flutter pub get

    - name: Run Tests
      if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: flutter test

    - name: Build Web App
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: flutter build web --wasm --base-href "${{ steps.pages.outputs.base_path }}/" --target "${{ inputs.build-target }}"

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ inputs.working-directory }}/build/web

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
